spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          #GIT远程仓库地址，这里是项目的路径，不是.git
          uri: https://github.com/git-mx/config
          #spring cloud config下载下来的文件保存的本地目录路径,在WINDOWS下要改成G:\config这样的
          basedir: /SrpingCloudConfig
          #git的账号密码
          username: git-mx
          password: mys160712
eureka:
  client:
    service-url:
      defaultZone: http://132.232.48.14:8761/eureka/

#咱们在访问有以下几种方式
#1.http://localhost:8080/order-a.yml  --master分支下的order.yml文件 后面的-a可以随便改，例如可以写成-b，但是必须要
#2.http://localhost:8080/order-a.properties --master分支下的会自动转换成porterties格式的文件
#3.http://localhost:8080/order-a.json --master分支下的会自动转换成JSON报文
#4.http://localhost:8080/order-dev.json --master分支下的下载的就是order-dev.yml
#5.http://localhost:8080/release/order-dev.json --release分支下的order-dev.json
#6.打包后部署到docker中去