spring:
  application:
    name: zk-server
  cloud:
    zookeeper:
      connect-string: 132.232.48.14:2181
      discovery:
        register: true
        enabled: true
        #instance-id: 1
        root: /spz
