version: "3"
services:
  eurekaService1:
    image: shyfay/eureka
    networks:
      - eureka-net
    ports:
      - "8761:8761"
    environment:
      - spring.profiles.active=eurekaService1
  eurekaService2:
    image: shyfay/eureka
    networks:
      - eureka-net
    ports:
      - "8762:8762"
    environment:
      - spring.profiles.active=eurekaService2
  eurekaService3:
    image: shyfay/eureka
    networks:
      - eureka-net
    ports:
      - "8763:8763"
    environment:
      - spring.profiles.active=eurekaService3
networks:
  eureka-net:
    driver: overlay