eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    #不将自身也注册成为client
    register-with-eureka: false
  server:
    #enreka server有一个健康检查机制，即当发现某一个注册的服务经常都不在线时，就会在
    #注册中心的管理界面抛出警告给运维人员查阅，我们在开发环境可以做如下设置，来关闭警告功能
    #但是生产环境最好保持该功能开启
    enable-self-preservation: false
server:
  port: 8761

#这里没有application.yml文件，但是有server1和server2两个文件，在右上角点击
#Edit Configuraion 然后在左上角的Spring Boot开面选中一个，点后点击左上角的copy Configuration
#然后分别明明为ApplicationStarter1和ApplicationStarter2
#然后选中ApplicationStarter1，选择右边Configuration-Enviroment-Environment variables-点击右侧文件夹图标
#然后在出来的窗体中点击右上角的+号,Name设置成spring.profiles.active,Value设置成application-server1.yml的后半段server1
#然后以此配置ApplicationStarter1设置成server2,
#注意观察server1和server2配置文件的区别