eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #不将自身也注册成为client
    register-with-eureka: false

  server:
    #enreka server有一个健康检查机制，即当发现某一个注册的服务经常都不在线时，就会在
    #注册中心的管理界面抛出警告给运维人员查阅，我们在开发环境可以做如下设置，来关闭警告功能
    #但是生产环境最好保持该功能开启
    enable-self-preservation: false
server:
  port: 8762