spring:
  profiles: eurekaService1
server:
  port: 8761
eureka:
  instance:
    hostname: eurekaService1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaService2:8762/eureka/,http://eurekaService3:8763/eureka/