spring:
  profiles: eurekaService3
server:
  port: 8763
eureka:
  instance:
    hostname: eurekaService3
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaService1:8761/eureka/,http://eurekaService2:8762/eureka/